#+TITLE: picom
#+AUTHOR: Bassam Saeed
#+PROPERTY: header-args  :comments both
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :tangle ~/.config/picom/picom.conf

An Xorg compositor that was forked from ~compton~ after than piece of
software became unmaintained. My usage of picom is pretty basic. I
don't require particularly fancy compositing.

* Basics
  Not sure I fully understand what these all do (except vsync), but
  these are settings the man page and people far more knowledgeable
  than me recommend as a starting point.

  #+begin_src conf
    backend = "glx";
    vsync = true;
    glx-no-stencil = true;
    glx-no-rebind-pixmap = true;
  #+end_src
* Bypass picom
  Bypassing picom when it detects a fullscreen application. Usually
  used to improve performance for games since they don't need a
  compositor.

  I don't particularly care for performance of that sort when watching
  video in fullscreen via mpv or celluloid and in particular I can't
  stand the slight stutter that happens when going to and from
  fullscreen. So I exclude those.

  #+begin_src conf
    unredir-if-possible = true;
    unredir-if-possible-exclude = [ "class_g *?= 'celluloid'", "class_g *?= 'mpv'" ];
  #+end_src

* Opacity
  For some reason I like when Emacs is slightly transparent when the
  active window. Maybe I'll look to applying this for all windows in
  the future, but for now I'm happy with Emacs.

  #+begin_src conf
    opacity-rule = [
		 "90:class_g = 'Emacs' && focused"
    ];
  #+end_src
