#+TITLE: Redshift
#+AUTHOR: Bassam Saeed

I use [[https://github.com/jonls/redshift][  Redshift]] to adjust the colour temperature of my screen. It's
inspired by ~f.lux~ and is helpful with blue light issues.

* Global Settings
  These are maximum and minimum values for the colour temperatures
  used during the day and night respectively.

  #+begin_src conf
    [redshift]
    temp-day=5700
    temp-night=3500
  #+end_src

  Gradually fade between temperatures when redshift starts and
  stops. I don't like the immediate change.

  #+begin_src conf
    fade=1
  #+end_src

  Redshift can use a location provider to determine the location for
  properly checking the position of the sun. I've set it to manual gps
  coordinates because this is only a desktop computer that stays in a
  fixed location.

  I want to integrate geoclue2 location provider for my laptops
  however.

  #+begin_src conf :tangle (when (equal (system-name) "polaris") "yes")
    location-provider: manual
  #+end_src

  The adjustment method I use is ~randr~ which is the newest and
  recommended method. The alternative is an older API called
  ~vidmode~. Not really sure what the difference is.

  #+begin_src conf
    adjustment-method=randr
  #+end_src
* Manual
  I could set these GPS coordinates specifically for ~polaris~ only, but
  I think it won't matter on the laptops because they wouldn't use
  these settings anyway.

  #+begin_src conf
    [manual]
    lat=43.595310
    lon=-79.640579
  #+end_src
