#+TITLE: Xorg
#+AUTHOR: Bassam Saeed
#+PROPERTY: header-args  :comments both
#+PROPERTY: header-args+ :tangle ~/.xinitrc

* xinitrc
  The ~xinit~ (and ~startx~) are handy utilities that allow setting up
  useful startup utilities and environment variables on X server
  startup. This is particularly useful when not using a Desktop
  Environment that would traditionally handle this for you.
  
** Basic defaults
   Not 100% certain where this is from. Think this is the default from
   ~/etc/X11/xinit/xinitrc~.
   
   #+begin_src bash
     userresources=$HOME/.Xresources
     usermodmap=$HOME/.Xmodmap
     sysresources=/etc/X11/xinit/.Xresources
     sysmodmap=/etc/X11/xinit/.Xmodmap

     # merge in defaults and keymaps

     if [ -f $sysresources ]; then
	 xrdb -merge $sysresources
     fi

     if [ -f $sysmodmap ]; then
	 xmodmap $sysmodmap
     fi

     if [ -f "$userresources" ]; then
	 xrdb -merge "$userresources"
     fi

     if [ -f "$usermodmap" ]; then
	 xmodmap "$usermodmap"
     fi

     # start some nice programs

     if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
	     [ -x "$f" ] && . "$f"
	 done
	 unset f
     fi
   #+end_src

** Nimf
   Alternative alphabet characters, such as CJK ones require an input
   method to allow Latin keyboards to input those alternative
   characters. I use Nimf for trying to learn Korean.

   #+begin_src bash
     export GTK_IM_MODULE=nimf
     export QT4_IM_MODULE="nimf"
     export QT_IM_MODULE=nimf
     export XMODIFIERS="@im=nimf"
     nimf
   #+end_src

** Start Window Manager
   And here I start my Window Manager. I used to include a lot of
   startup applications and environment variables, but I realized that
   often that can be heavily dependent on the window manager itself so
   I transitioned those the window manager startup config.

   #+begin_src bash
     exec bspwm
   #+end_src
