#!/usr/bin/env bash

xsetroot -cursor_name left_ptr &
sxhkd &

bspc config border_width	2
bspc config window_gap		10
bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true

for monitor in $(bspc query -M --names); do
    bspc monitor $monitor -d १ २ ३ ४ ५
    Monitor=$monitor polybar & disown
done

bspc rule -a Firefox desktop=^1
bspc rule -a Emacs state=tiled
bspc rule -a mpv state=floating

polybar & disown

[[ "$HOSTNAME" == "polaris" ]] && guix shell xrandr -- xrandr --output DisplayPort-0 --primary --auto --output HDMI-A-0 --auto --mode 1920x1080 --rate 165.00 --left-of DisplayPort-0
guix shell setroot -- setroot --restore
guix shell xset -- xset -b
