#! /bin/sh

sxhkd &

#xrandr --output HDMI2 --above eDP1
if [ "$(xrandr | grep HDMI2 | cut -d' ' -f2)" = "connected" ]; then
    xrandr --output eDP1 --off
fi

setroot --restore

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

monitors=$(bspc query -M)

for i in $monitors
do
    bspc monitor "$i" -d I II III IV V
done

bspc config border_width            5
bspc config normal_border_color     "#a5a3c6"
bspc config focused_border_color    "#ae8688"
bspc config window_gap              20

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config click_to_focus          true

bspc rule -a Firefox desktop=^1
bspc rule -a mpv state=floating
bspc rule -a Emacs state=tiled

if [ "$(bspc query -M | wc -l)" -gt 1 ]; then
    enforce_monitor_position eDP1 '^1' &
fi
