#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus      true

bspc rule -a Firefox desktop='^1'
bspc rule -a mpv state=floating
bspc rule -a imv state=floating
