#!/usr/bin/env bash

xsetroot -cursor_name left_ptr &

setxkbmap -option 'caps:ctrl_modifier'
xcape -e 'Caps_Lock=Escape'

sxhkd &
picom -b

source "$HOME/.themes/Rose-pine-bspwm/rose-pine-dawn"

bspc monitor HDMI-A-0 -d I II III IV
bspc monitor DisplayPort-0 -d V VI VII VIII

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop=^1
bspc rule -a Emacs state=tiled
bspc rule -a mpv state=floating

xrandr --output HDMI-A-0 --primary --auto --output DisplayPort-0 --auto --mode 1920x1080 --rate 165.00 --right-of HDMI-A-0 --rotate right
setroot --restore

redshift &
