#! /bin/sh

xsetroot -cursor_name left_ptr &
sxhkd &

setroot --restore
xrandr --output HDMI-A-0 --primary --auto --output DisplayPort-0 --auto --mode 1920x1080 --rate 165.00 --pos 3840x240 --rotate right
picom -b

bspc monitor HDMI-A-0 -d I II III IV
bspc monitor DisplayPort-0 -d V VI VII VIII

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Emacs state=tiled
bspc rule -a mpv state=floating

#Dracula Colour Scheme
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
