#!/bin/sh
. panel_colors

wifi_ssid(){
    NAME=$(iw dev wlo1 link | grep SSID | sed 's/.*: //')
    if [ "$NAME" == "" ]; then
        echo "%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}$(printf '%b' "")%{B-}%{F-} no conn"
    else echo "%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}$(printf '%b' "")%{B-}%{F-} $NAME"
    fi
}

battery(){
    bat_info=$(acpi -b | cut -d, -f2 | cut -d' ' -f2 | cut -d% -f1)
    
    fg_color=$COLOR_STATUS_FG
    bg_color=$COLOR_STATUS_BG

    if [ $(acpi -b | cut -d' ' -f3 | cut -d, -f1) == "Discharging" ]; then
        fg_color=$COLOR_URGENT_FG
        bg_color=$COLOR_URGENT_BG
    fi

    if [ $bat_info -eq 100 ]; then
        echo "%{F$fg_color}%{B$bg_color} "" $bat_info% %{B-}%{F-}"
    elif [ $bat_info -gt 75 ]; then
        echo "%{F$fg_color}%{B$bg_color} "" $bat_info% %{B-}%{F-}"
    elif [ $bat_info -gt 50 ]; then
        echo "%{F$fg_color}%{B$bg_color} "" $bat_info% %{B-}%{F-}"
    elif [ $bat_info -gt 25 ]; then
        echo "%{F$fg_color}%{B$bg_color} "" $bat_info% %{B-}%{F-}"
    else echo "%{F$fg_color}%{B$bg_color} "" $bat_info% %{B-}%{F-}"
    fi
}

datetime(){
    echo $(clock -f ' %A, %b %d   %H:%M')
}

while :; do
    echo "S$(wifi_ssid)$(battery)$(datetime)"
    sleep 2
done
