#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

num_mon=$(bspc query -M) # determine number of monitors
PANEL_HEIGHT=24
PANEL_FONT_FAMILY="tewi:size=10"

x_Offset=0

bspc config top_padding $PANEL_HEIGHT

. panel_colors

for i in $num_mon; do
	# remove any open panel fifo and create a new one
	[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
	mkfifo "$PANEL_FIFO"

	bspc control --subscribe |
		grep -oE "[Mm]$i[^TM]*[TML]" --line-buffered |
		while read line; do echo W$line; done  > "$PANEL_FIFO" &

	xtitle -sf 'T%s' > "$PANEL_FIFO" &
	clock -sf "S%a %d %b %H:%M" > "$PANEL_FIFO" &

	monitor_width=$(bspc query -T -m $i | grep -oE "[0-9]{2,6}" | head -n 1)
	
	cat "$PANEL_FIFO" | panel_bar |	lemonbar -g "$monitor_width"x"$PANEL_HEIGHT"+"$x_Offset" -f "$PANEL_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

	x_Offset=$(expr $x_Offset + $monitor_width)

done

wait
