#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

while read -r line ; do
    case $line in
        S*)
            # clock output
            sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG} ${line#?}%{B-}%{F-}"
            ;;
        T*)
            # xtitle output
            title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
            ;;
    esac
    printf "%s\n" "%{l}${wm_infos}%{c}${title}%{r}${sys_infos}"
done
