#+TITLE: Remove Package
#+AUTHOR: Bassam Saeed
#+PROPERTY: header-args  :comments both
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :tangle ~/bin/removePackage.sh
#+PROPERTY: header-args+ :shebang "#!/usr/bin/env bash"

This properly removes a package installed from the ~AUR~ via [[https://github.com/AladW/aurutils][
aurutils]]. I'm thinking of moving away from aurutils so this will
likely just be a historical artifact in my repo.

aurutils is an interesting collection of tools to handle ~AUR~
packages. It's flexibility and power really appeal to me. Ultimately I
realized that I didn't really use or need that additional
flexibility. At its core my usage is fairly basic and plenty of other
aur helpers handle it perfectly without the extra headache that can
something come with the power of aurutils.

* Usage
  Extract out the comments at the top of the script.
  
  #+begin_src bash
    ### removePackage.sh --- properly remove packages installed using AURUTILS
    ###
    ### Usage:
    ###   removePackage.sh <pkgname>
    ###
    ### Options:
    ###   <pkgname>   Name of the AUR package to remove

    help() {
	sed -n 's/^### \?//p' "$0"
    }
  #+end_src
* Handle options
  Probably should have used getopts but whatever.

  #+begin_src bash
    if [[ $# == 0 ]] || [[ "$1" == "-h" ]]; then
	help
	exit 1
    fi
  #+end_src
* Remove a package
  This is pretty limited. Should have expanded it to handle multiple
  packages at once and not hardcoded the repository.

  It removes the package from the custom repo and then uninstalls the
  package and clears the package cache for good measure.

  #+begin_src bash
    repo-remove /home/custompkgs/custom.db.tar $1
    sudo pacman -Rs $1
    sudo paccache -r
  #+end_src
