#+TITLE: wallpaper
#+AUTHOR: Bassam Saeed
#+PROPERTY: header-args  :comments both
#+PROPERTY: header-args+ :mkdirp yes
#+PROPERTY: header-args+ :tangle ~/bin/wallpaper.sh
#+PROPERTY: header-args+ :shebang "#!/usr/bin/env bash"

Shows all wallpapers in ~pqiv~ and allow for setting them as a desktop
background using ~setroot~.

* Usage
  Extract out ~###~ comments to create the help menu.

  #+begin_src bash
    ### wallpaper.sh --- Allow setting wallpapers using pqiv and setroot
    ###
    ### Usage:
    ###   wallpaper.sh
    ###
    ### Options:
    ###   -h show this help

    usage() {
	sed -n 's/^### \?//p' "$0"
    }
  #+end_src
* Handle options
  Really the only option we need is the help menu. By default I don't
  really see what other options would be needed.

  #+begin_src bash
    while getopts ':h' OPT; do
	case ${OPT} in
	    h) usage
	       exit 0
	       ;;
	    \?) echo "Invalid option: -$OPTARG" 1>&2
		exit 1
		;;
	esac
    done

    shift "$((OPTIND -1))"
  #+end_src
* TODO Determine wallpapers directory
  Basically the expanded idea I have is that in order to handle the
  different resolutions and ratios of my setups, I'll separate out my
  wallpapers in separate directories based on the ratio. Then I'll use
  xrandr to live calculate the resolution and show wallpapers only in
  the appropriate directory.

  #+begin_src bash
    RESOLUTION=$(xrandr | grep 'current' | awk '{print $8$9$10}' | cut -d, -f1) # not used right now
    WALLPAPER_DIR="$HOME/media/images/wallpapers"
  #+end_src
* Start pqiv
  Now that we have the wallpaper directory, we can start ~pqiv~ in
  montage mode to show all the wallpapers. Right now the keybind to
  automatically set the wallpaper only happens when the wallpaper is
  selected. I want to also set the keybind to work in montage mode
  directly but right now I'm not certain how to get the filename of
  the wallpaper under the /cursor/.

  #+begin_src bash
    pqiv --auto-montage-mode --thumbnail-persistence=yes --thumbnail-size=256x256 --bind-key="w { command(setroot --store -t $1) }" $WALLPAPER_DIR/*
  #+end_src
